// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: string
}

export type CreateUserDto = {
  /**
   * 用户标识
   */
  id: number
  /**
   * 用户名
   */
  username: string
  /**
   * 昵称
   */
  nickname: string
  /**
   * 电子邮箱
   */
  email: string
  /**
   * 手机号码
   */
  telephone: string
  /**
   * 状态
   */
  status?: number
  /**
   * 密码
   */
  password: string
  /**
   * 角色id集合
   */
  rolesId: Array<string>
}

export type LoginDto = {
  /**
   * 用户名
   */
  username: string
  /**
   * 密码
   */
  password: string
}

export type CreateMenuDto = {
  [key: string]: unknown
}

export type UpdateMenuDto = {
  [key: string]: unknown
}

export type CreateRoleDto = {
  roleName: string
  remark?: string
  /**
   * 角色状态，1表示启用，0表示禁用
   */
  status: number
  menuIds?: Array<string>
  roleSort: number
  createBy: number
  updateBy: number
}

export type GetRoleListDto = {
  roleName: string
  /**
   * 角色状态，1表示启用，0表示禁用
   */
  status: number
  menus: Array<string>
  /**
   * 创建时间筛选开始日期时间戳
   */
  startCreateDate?: number
  /**
   * 创建时间筛选结束日期时间戳
   */
  endCreateDate?: number
  /**
   * 页码
   */
  currentPage: number
  /**
   * 页面大小
   */
  pageSize: number
}

export type UpdateRoleDto = {
  roleName?: string
  remark?: string
  /**
   * 角色状态，1表示启用，0表示禁用
   */
  status?: number
  menuIds?: Array<string>
  roleSort?: number
  createBy?: number
  updateBy?: number
}

export type GetHelloData = {
  body?: never
  path?: never
  query?: never
  url: '/'
}

export type GetHelloResponses = {
  200: unknown
}

export type RegisterData = {
  body: CreateUserDto
  path?: never
  query?: never
  url: '/user/register'
}

export type RegisterResponses = {
  201: unknown
}

export type LoginData = {
  body: LoginDto
  path?: never
  query?: never
  url: '/user/login'
}

export type LoginResponses = {
  /**
   * 返回示例
   */
  200: LoginDto
}

export type LoginResponse = LoginResponses[keyof LoginResponses]

export type GetCaptchaData = {
  body?: never
  path?: never
  query?: never
  url: '/user/captcha'
}

export type GetCaptchaResponses = {
  200: unknown
}

export type GetInfoData = {
  body?: never
  path?: never
  query?: never
  url: '/user/getInfo'
}

export type GetInfoResponses = {
  200: unknown
}

export type CreateUserByAdminData = {
  body: CreateUserDto
  path?: never
  query?: never
  url: '/user'
}

export type CreateUserByAdminResponses = {
  201: unknown
}

export type UpdateUserData = {
  body: CreateUserDto
  path?: never
  query?: never
  url: '/user'
}

export type UpdateUserResponses = {
  200: unknown
}

export type DeleteUserData = {
  body?: never
  path: {
    userId: number
  }
  query?: never
  url: '/user/{userId}'
}

export type DeleteUserResponses = {
  200: unknown
}

export type ListData = {
  body?: never
  path?: never
  query: {
    /**
     * 用户名
     */
    username: string
    /**
     * 用户昵称
     */
    nickname: string
    /**
     * 手机号码
     */
    telephone: string
    /**
     * 用户状态
     */
    status: number
    /**
     * 页码
     */
    currentPage: number
    /**
     * 页面大小
     */
    pageSize: number
  }
  url: '/user/list'
}

export type ListResponses = {
  200: unknown
}

export type CreateMenuData = {
  body: CreateMenuDto
  path?: never
  query?: never
  url: '/menu'
}

export type CreateMenuResponses = {
  201: unknown
}

export type GetRoutersData = {
  body?: never
  path?: never
  query?: never
  url: '/menu/getRouters'
}

export type GetRoutersResponses = {
  200: unknown
}

export type GetMenuTreeData = {
  body?: never
  path?: never
  query?: never
  url: '/menu/info'
}

export type GetMenuTreeResponses = {
  200: unknown
}

export type GetUserButtonPermissionsData = {
  body?: never
  path?: never
  query?: never
  url: '/menu/buttonPermissions'
}

export type GetUserButtonPermissionsResponses = {
  200: unknown
}

export type FindByPageData = {
  body?: never
  path?: never
  query: {
    /**
     * 页码
     */
    currentPage: number
    /**
     * 页面大小
     */
    pageSize: number
  }
  url: '/menu/menusByPage'
}

export type FindByPageResponses = {
  200: unknown
}

export type DeleteMenuData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/menu/{id}'
}

export type DeleteMenuResponses = {
  200: unknown
}

export type GetMenuDetailData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/menu/{id}'
}

export type GetMenuDetailResponses = {
  200: unknown
}

export type UpdateMenuData = {
  body: UpdateMenuDto
  path: {
    id: number
  }
  query?: never
  url: '/menu/{id}'
}

export type UpdateMenuResponses = {
  200: unknown
}

export type RemoveWithChildrenData = {
  body?: never
  path: {
    id: number
  }
  query?: never
  url: '/menu/{id}/cascade'
}

export type RemoveWithChildrenResponses = {
  200: unknown
}

export type CreateRoleData = {
  body: CreateRoleDto
  path?: never
  query?: never
  url: '/role'
}

export type CreateRoleResponses = {
  201: unknown
}

export type GetRolesByPageData = {
  body?: never
  path?: never
  query: {
    roleName: string
    /**
     * 角色状态，1表示启用，0表示禁用
     */
    status: number
    menus: Array<string>
    /**
     * 创建时间筛选开始日期时间戳
     */
    startCreateDate?: number
    /**
     * 创建时间筛选结束日期时间戳
     */
    endCreateDate?: number
    /**
     * 页码
     */
    currentPage: number
    /**
     * 页面大小
     */
    pageSize: number
  }
  url: '/role/rolesByPage'
}

export type GetRolesByPageResponses = {
  200: unknown
}

export type GetRolesListData = {
  body?: never
  path?: never
  query?: never
  url: '/role/allRoles'
}

export type GetRolesListResponses = {
  /**
   * 返回示例
   */
  200: Array<GetRoleListDto>
}

export type GetRolesListResponse = GetRolesListResponses[keyof GetRolesListResponses]

export type DeleteRoleData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/role/{id}'
}

export type DeleteRoleResponses = {
  200: unknown
}

export type GetRoleByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/role/{id}'
}

export type GetRoleByIdResponses = {
  200: unknown
}

export type UpdateRoleData = {
  body: UpdateRoleDto
  path: {
    id: string
  }
  query?: never
  url: '/role/{id}'
}

export type UpdateRoleResponses = {
  200: unknown
}
