/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: (typeof import('element-plus/es'))['ElAside']
    ElBacktop: (typeof import('element-plus/es'))['ElBacktop']
    ElBadge: (typeof import('element-plus/es'))['ElBadge']
    ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb']
    ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElColorPicker: (typeof import('element-plus/es'))['ElColorPicker']
    ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider']
    ElContainer: (typeof import('element-plus/es'))['ElContainer']
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown']
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem']
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElHeader: (typeof import('element-plus/es'))['ElHeader']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElMain: (typeof import('element-plus/es'))['ElMain']
    ElMenu: (typeof import('element-plus/es'))['ElMenu']
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
    ElPopover: (typeof import('element-plus/es'))['ElPopover']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElTabPane: (typeof import('element-plus/es'))['ElTabPane']
    ElTabs: (typeof import('element-plus/es'))['ElTabs']
    ElTooltip: (typeof import('element-plus/es'))['ElTooltip']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
