packages:
  - apps/*
  - packages/*

catalog:
  '@ctrl/tinycolor': ^4.1.0
  '@element-plus/icons-vue': ^2.3.1
  '@hey-api/client-axios': ^0.9.1
  '@iconify/vue': ^5.0.0
  '@nestjs/config': ^4.0.2
  '@nestjs/jwt': ^11.0.0
  '@nestjs/swagger': ^11.2.0
  '@nestjs/typeorm': ^11.0.0
  '@tailwindcss/vite': ^4.1.11
  '@types/lodash.clonedeep': ^4.5.9
  '@types/nprogress': ^0.2.3
  '@vitejs/plugin-vue': ^6.0.0
  '@vitejs/plugin-vue-jsx': ^5.1.1
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^13.6.0
  axios: 1.11.0
  class-transformer: ^0.5.1
  class-validator: ^0.14.2
  crypto: ^1.0.1
  dayjs: ^1.11.13
  defu: ^6.1.4
  element-plus: 2.10.4
  lodash: ^4.17.21
  lodash.clonedeep: ^4.5.0
  mysql2: ^3.14.3
  nestjs-typeorm-paginate: ^4.1.0
  nprogress: ^0.2.0
  pinia: 3.0.3
  pinia-plugin-persistedstate: 4.4.1
  redis: ^5.8.1
  sass: ^1.89.2
  screenfull: ^6.0.2
  svg-captcha: ^1.4.0
  tailwindcss: ^4.1.11
  theme-colors: 0.1.0
  typeorm: ^0.3.25
  typeorm-naming-strategies: ^4.1.0
  typescript: ~5.8.3
  unplugin-auto-import: 0.17.8
  unplugin-vue-components: ~0.26.0
  vite: 7.0.5
  vite-plugin-svg-icons: ^2.0.1
  vue: ^3.5.17
  vue-i18n: ^11.1.11
  vue-router: ^4.5.1
  vue-tsc: 2.2.12
