packages:
  - apps/*
  - packages/*

catalog:
  '@element-plus/icons-vue': ^2.3.1
  '@iconify/vue': ^5.0.0
  '@tailwindcss/vite': ^4.1.11
  '@vitejs/plugin-vue': ^6.0.0
  '@vue/tsconfig': ^0.7.0
  element-plus: 2.10.4
  lodash: ^4.17.21
  sass: ^1.89.2
  screenfull: ^6.0.2
  tailwindcss: ^4.1.11
  typescript: ~5.8.3
  unplugin-auto-import: 0.17.8
  unplugin-vue-components: ~0.26.0
  vite: ^7.0.5
  vite-plugin-svg-icons: ^2.0.1
  vue: ^3.5.17
  vue-router: ^4.5.1
  vue-tsc: 2.2.12
